#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/xchg.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"

#include "string/rep.h"

#include "misc/misc.h"

#include "special/special.h"

#include "fbd/push.h"
#include "fbd/call.h"
#include "fbd/test.h"
#include "fbd/je.h"
#include "fbd/pop.h"
#include "fbd/ret.h"
#include "fbd/add.h"
#include "fbd/cmp.h"
#include "fbd/sub.h"
#include "fbd/sbb.h"
#include "fbd/jmp.h"
#include "fbd/jbe.h"
#include "fbd/jle.h"
#include "fbd/jl.h"
#include "fbd/ja.h"
#include "fbd/jg.h"
#include "fbd/js.h"
#include "fbd/jns.h"
#include "fbd/jge.h"
#include "fbd/clt.h"
#include "fbd/jne.h"
#include "fbd/leave.h"
#include "fbd/lea.h"
#include "fbd/adc.h"
#include "fbd/movzb.h"
#include "fbd/movzw.h"
#include "fbd/cmovs.h"
#include "fbd/movsb.h"
#include "fbd/movsw.h"
#include "fbd/movs.h"
#include "fbd/setne.h"
#include "fbd/nop.h"
#include "fbd/lods.h"
#include "fbd/scas.h"
#include "fbd/stos.h"
#include "fbd/lgdt.h"
#include "fbd/std.h"
#include "fbd/cld.h"

#include "fbd/PA4/lidt.h"
#include "fbd/PA4/pusha.h"
#include "fbd/PA4/popa.h"
#include "fbd/PA4/cli.h"
#include "fbd/PA4/iret.h"
#include "fbd/PA4/int.h"
#include "fbd/PA4/sete.h"
#include "fbd/PA4/setge.h"
#include "fbd/PA4/in.h"
#include "fbd/PA4/out.h"
#include "fbd/PA4/hlt.h"
#include "fbd/PA4/sti.h"
#include "fbd/PA4/jae.h"
#include "fbd/PA4/jb.h"
#include "fbd/PA4/cmove.h"
#include "fbd/PA4/cmovle.h"
#include "fbd/PA4/bt.h"

